### ISSUE TITLE
Can't play (keyboard keys are not responsive in the game)

### ISSUE THREAD

**Issue by frenchbread** [vaniacer/piu-piu-SH#9]
Pressing keyboard keys does not lead to anything (game freezes after startup).

### Screenshot:

<img width="1440" alt="screen shot 2017-09-17 at 15 31 23" src="https://user-images.githubusercontent.com/2122679/30520789-5b607758-9bbd-11e7-96a3-4372953f7f7c.png">

I'm using [iTerm](https://www.iterm2.com/version3.html) with [oh-my-zsh](https://github.com/robbyrussell/oh-my-zsh)

**Comment by vaniacer** [comment]
I'm afraid it's not supported.

**Comment by Self-Perfection** [comment]
@frenchbread but you do have bash in your system and this game needs bash. If you ran the game as `./piu-piu`, then shebang (first line with `#!` of script) defines which interpreter is used and thus uses bash.

Anyway you can use specific interpreter:
`bash ./piu-piu`

Most likely the issue is that you have ancient bash version. To check:
`bash -c 'echo ${BASH_VERSION}'`

The game needs at least 4.2

**Comment by frenchbread** [comment]
@Self-Perfection Thanks for your comment. I upgraded to `bash-4.4`, switched to it, and ran the game with it `bash-4.4$ bash ./piu-piu`, getting same result.

**Comment by Self-Perfection** [comment]
Your prompt string does not convince me that this command launched bash 4.4. Please do copy-paste here how do you check this. For instance here is my system:
```
$ bash -c 'echo ${BASH_VERSION}'
4.4.7(1)-release
```
Also please specify with which version do you have this issue: `git --no-pager log -1 --format='%h %ai'`. You might want to pull more recent version.

**Comment by frenchbread** [comment]
Right, I did pull latest changes now and was able to play. Thanks!!
